# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLyWRHgL53flOafcJkbPsSUOkB8FdQwU
"""

# Task4_Data_Visualization.py
# Create charts and a dashboard using matplotlib

import pandas as pd
import matplotlib.pyplot as plt
import os

#Step 1: Load Data -------- #

file_path = "data/trends_analysed.csv"
df = pd.read_csv(file_path)

# Create outputs folder if not exists
os.makedirs("outputs", exist_ok=True)


#Chart 1: Top 10 Stories by Score --------

top10 = df.sort_values(by="score", ascending=False).head(10)

# Shorten long titles
top10["short_title"] = top10["title"].apply(
    lambda x: x[:50] + "..." if len(x) > 50 else x
)

plt.figure()
plt.barh(top10["short_title"], top10["score"])
plt.xlabel("Score")
plt.ylabel("Title")
plt.title("Top 10 Stories by Score")
plt.gca().invert_yaxis()

plt.savefig("outputs/chart1_top_stories.png")
plt.close()


#Chart 2: Stories per Category --------

category_counts = df["category"].value_counts()

plt.figure()
plt.bar(category_counts.index, category_counts.values,
        color=["blue", "green", "red", "purple", "orange"])
plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.title("Stories per Category")

plt.savefig("outputs/chart2_categories.png")
plt.close()


#Chart 3: Score vs Comments --------

plt.figure()

# Split popular and non-popular
popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

plt.scatter(popular["score"], popular["num_comments"], label="Popular")
plt.scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")

plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.title("Score vs Comments")
plt.legend()

plt.savefig("outputs/chart3_scatter.png")
plt.close()


#Bonus: Dashboard --------

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# Chart 1
axes[0].barh(top10["short_title"], top10["score"])
axes[0].set_title("Top Stories")
axes[0].invert_yaxis()

# Chart 2
axes[1].bar(category_counts.index, category_counts.values)
axes[1].set_title("Categories")

# Chart 3
axes[2].scatter(popular["score"], popular["num_comments"], label="Popular")
axes[2].scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")
axes[2].set_title("Score vs Comments")
axes[2].legend()

fig.suptitle("TrendPulse Dashboard")

plt.savefig("outputs/dashboard.png")
plt.close()


print("All charts saved in 'outputs/' folder successfully.")