# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMT7kAcVClXWdxmAvoaj7oX-ME7yWXlW
"""

# Task3_Data_Analysis.py
# Analyse cleaned data and add new columns

import pandas as pd
import numpy as np

# Step 1: Load and Explore --------

file_path = "data/trends_clean.csv"

df = pd.read_csv(file_path)

# print("First 5 rows:\n")
print(df.head())

# print("\nShape of data (rows, columns):")
print(df.shape)

print(df["score"].mean())
print(df["num_comments"].mean())


# Step 2: Analysis using NumPy --------

scores = df["score"].values

print("\nScore statistics:")
print("Mean:", np.mean(scores))
print("Median:", np.median(scores))
print("\nHighest score:", np.max(scores))
print("Lowest score:", np.min(scores))

# Category with most stories
print("\nCategory with most stories:")
print(df["category"].value_counts().idxmax())

# Story with most comments
top_story = df.loc[df["num_comments"].idxmax()]
print("\nMost commented story:")
print("Title:", top_story["title"])
print("Comments:", top_story["num_comments"])


# Step 3: Add New Columns --------

# Engagement = comments per score
df["engagement"] = df["num_comments"] / (df["score"] + 1)

# Popular if score > average score
avg_score = df["score"].mean()
df["is_popular"] = df["score"] > avg_score


# Step 4: Save Result --------

output_path = "data/trends_analysed.csv"

df.to_csv(output_path, index=False)

print(f"\nSaved analysed data to {output_path}")